# Generated by Django 6.0.3 on 2026-04-01 09:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rifugio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('localita', models.CharField(max_length=200)),
                ('altitudine', models.IntegerField()),
                ('latitudine', models.FloatField()),
                ('longitudine', models.FloatField()),
                ('regione', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('RIFUGIO', 'Rifugio'), ('BIVACCO', 'Bivacco'), ('CAPANNA', 'Capanna')], default='RIFUGIO', max_length=20)),
                ('descrizione', models.TextField(blank=True)),
                ('posti_letto', models.IntegerField(default=0)),
                ('posti_disponibili', models.IntegerField(default=0)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='rifugi/')),
                ('qr_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stato', models.CharField(choices=[('in_attesa', 'In attesa'), ('approvato', 'Approvato')], default='in_attesa', max_length=20)),
                ('gestore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rifugi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('voto', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('escursionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to=settings.AUTH_USER_MODEL)),
                ('rifugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='rifugi.rifugio')),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_arrivo', models.DateField()),
                ('data_partenza', models.DateField()),
                ('num_ospiti', models.IntegerField(default=1)),
                ('stato', models.CharField(choices=[('in_attesa', 'In attesa'), ('approvata', 'Approvata'), ('rifiutata', 'Rifiutata')], default='in_attesa', max_length=20)),
                ('escursionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to=settings.AUTH_USER_MODEL)),
                ('rifugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to='rifugi.rifugio')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visita', models.DateTimeField(auto_now_add=True)),
                ('escursionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visite', to=settings.AUTH_USER_MODEL)),
                ('rifugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visite', to='rifugi.rifugio')),
            ],
            options={
                'unique_together': {('escursionista', 'rifugio')},
            },
        ),
        migrations.CreateModel(
            name='Timbro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_assegnazione', models.DateTimeField(auto_now_add=True)),
                ('visita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timbro', to='rifugi.visita')),
            ],
        ),
        migrations.CreateModel(
            name='Preferito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('escursionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferiti', to=settings.AUTH_USER_MODEL)),
                ('rifugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferiti', to='rifugi.rifugio')),
            ],
            options={
                'unique_together': {('escursionista', 'rifugio')},
            },
        ),
    ]
