# Generated by Django 6.0.3 on 2026-07-05 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifugi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prenotazione',
            options={'verbose_name_plural': 'Prenotazioni'},
        ),
        migrations.AlterModelOptions(
            name='recensione',
            options={'verbose_name_plural': 'Recensioni'},
        ),
        migrations.AlterModelOptions(
            name='rifugio',
            options={'verbose_name_plural': 'Rifugi'},
        ),
        migrations.AlterModelOptions(
            name='timbro',
            options={'verbose_name_plural': 'Timbri'},
        ),
        migrations.AlterModelOptions(
            name='visita',
            options={'verbose_name_plural': 'Visite'},
        ),
        migrations.AlterUniqueTogether(
            name='preferito',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True)),
                ('data', models.DateField()),
                ('ora', models.TimeField(blank=True, null=True)),
                ('posti_disponibili', models.IntegerField(default=0)),
                ('rifugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi', to='rifugi.rifugio')),
            ],
            options={
                'verbose_name_plural': 'Eventi',
                'ordering': ['data'],
            },
        ),
        migrations.RemoveField(
            model_name='preferito',
            name='data',
        ),
    ]
