# Generated by Django 6.0.3 on 2026-07-05 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifugi', '0002_alter_prenotazione_options_alter_recensione_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True)),
                ('data', models.DateField()),
                ('ora', models.TimeField(blank=True, null=True)),
                ('difficolta', models.CharField(choices=[('facile', 'Facile'), ('medio', 'Medio'), ('difficile', 'Difficile'), ('esperto', 'Esperto')], default='facile', max_length=20)),
                ('posti_disponibili', models.IntegerField(default=0)),
                ('guida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerari', to=settings.AUTH_USER_MODEL)),
                ('rifugi', models.ManyToManyField(blank=True, related_name='itinerari', to='rifugi.rifugio')),
            ],
            options={
                'verbose_name_plural': 'Itinerari',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='IscrizioneItinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_iscrizione', models.DateTimeField(auto_now_add=True)),
                ('escursionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iscrizioni_itinerari', to=settings.AUTH_USER_MODEL)),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iscrizioni', to='rifugi.itinerario')),
            ],
            options={
                'verbose_name_plural': 'Iscrizioni Itinerari',
                'unique_together': {('escursionista', 'itinerario')},
            },
        ),
    ]
