# Generated by Django 6.0.3 on 2026-07-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifugi', '0003_itinerario_iscrizioneitinerario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='eventi/'),
        ),
    ]
