# Generated by Django 6.0.3 on 2026-07-10 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifugi', '0004_evento_immagine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IscrizioneEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_iscrizione', models.DateTimeField(auto_now_add=True)),
                ('escursionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iscrizioni_eventi', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iscrizioni', to='rifugi.evento')),
            ],
            options={
                'verbose_name_plural': 'Iscrizioni Eventi',
                'unique_together': {('escursionista', 'evento')},
            },
        ),
    ]
