# Generated by Django 6.0.3 on 2026-07-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifugi', '0005_iscrizioneevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='iscrizioneevento',
            name='num_persone',
            field=models.IntegerField(default=1),
        ),
    ]
