# Generated by Django 6.0.3 on 2026-07-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rifugi', '0006_iscrizioneevento_num_persone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iscrizioneevento',
            name='num_persone',
        ),
    ]
