# Generated by Django 6.0.3 on 2026-07-11 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifugi', '0007_remove_iscrizioneevento_num_persone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfiloGuida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='guide/')),
                ('guida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profilo_guida', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
