# Generated by Django 6.0.3 on 2026-07-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifugi', '0008_profiloguida'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='posti_restituiti',
            field=models.BooleanField(default=False),
        ),
    ]
