# Generated by Django 6.0.3 on 2026-07-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifugi', '0009_prenotazione_posti_restituiti'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifugio',
            name='mensile',
            field=models.BooleanField(default=False),
        ),
    ]
