# Generated by Django 6.0.3 on 2026-07-14 08:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rifugi', '0010_rifugio_mensile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferito',
            options={'verbose_name_plural': 'Preferiti'},
        ),
        migrations.AlterUniqueTogether(
            name='preferito',
            unique_together={('escursionista', 'rifugio')},
        ),
        migrations.AlterUniqueTogether(
            name='recensione',
            unique_together={('escursionista', 'rifugio')},
        ),
    ]
