# Generated by Django 6.0.3 on 2026-07-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rifugi', '0011_alter_preferito_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visita',
            unique_together=set(),
        ),
    ]
