# Generated by Django 6.0.3 on 2026-07-14 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifugi', '0012_alter_visita_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timbro',
            name='escursionista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timbri', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timbro',
            name='rifugio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='timbri', to='rifugi.rifugio'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='timbro',
            name='visita',
        ),
        migrations.AlterUniqueTogether(
            name='timbro',
            unique_together={('escursionista', 'rifugio')},
        ),
    ]
